### ISSUE TITLE
chef-provisioning-rackspace

### ISSUE THREAD

**Issue by jjasghar** [rackspace-cookbooks/rackspacecloud#34]
With this cookbook you aren't far from being able to create a chef-provisioning-rackspace driver.

**Comment by martinb3** [comment]
I had heard at one point that there was interest in unifying chef-provisioning drivers and test-kitchen drivers too. I was secretly hoping for that :)

**Comment by jjasghar** [comment]
Just gonna leave this [here](https://github.com/chef/chef-provisioning/blob/master/docs/building_drivers.md#writing-drivers).

**Comment by jjasghar** [comment]
I'm closing this because it seems https://github.com/chef/chef-provisioning-fog/#rackspace does the heavy lifting!
